data_science:
  n_qubits: 10
  loss_func: MSELoss
  epochs: 2
  learning_rate: 0.03
  two_optimizers: True
  TEST_SIZE: ${TEST_SIZE}
  TRAINING_SIZE: ${TRAINING_SIZE}
  number_classes: ${number_classes}
  
