data_science:
  loss_func: CrossEntropyLoss
  n_qubits: ${n_qubits}
  n_layers: ${n_layers}
  epochs: 3
  optimizer:
    # combined:
    #   name: SGD
    #   lr: 0.03
    classical:
      name: SGD
      lr: 0.03
    quantum:
      name: Adam
      lr: 0.04
  optimizer_range:
    combined:
      name: [SGD, Adam, NGD]
      lr: [0.01, 0.1, 'log']
    classical:
      name: [SGD, Adam, NGD]
      lr: [0.01, 0.1, 'log']
    quantum:
      name: [SGD, Adam, NGD, QNG, SPSA]
      lr: [0.01, 0.1, 'log']
  TEST_SIZE: ${TEST_SIZE}
  TRAINING_SIZE: ${TRAINING_SIZE}
  classes: ${classes}
  
