data_science:
  wires: ${wires}
  loss_func: CrossEntropyLoss
  epochs: 2
  learning_rate: 0.03
  two_optimizers: True
  TEST_SIZE: ${TEST_SIZE}
  TRAINING_SIZE: ${TRAINING_SIZE}
  number_classes: ${number_classes}
  
