data_science:
  n_qubits: ${n_qubits}
  loss_func: MSELoss
  epochs: 2
  learning_rate: 0.03
  optimizer_list: [SGD]
  TEST_SIZE: ${TEST_SIZE}
  TRAINING_SIZE: ${TRAINING_SIZE}
  number_classes: ${number_classes}
  
